mongoexport.exe --uri="XXX" --collection=team-stats --out=team-stats.json
mongoexport.exe --uri="XXX" --collection=player-stats --out=player-stats.json
mongoexport.exe --uri="XXX" --collection=bans --out=bans.json
mongoexport.exe --uri="XXX" --collection=challenges --out=challenges.json
mongoexport.exe --uri="XXX" --collection=lineup-queues --out=lineup-queues.json
mongoexport.exe --uri="XXX" --collection=lineups --out=lineups.json
mongoexport.exe --uri="XXX" --collection=matches --out=matches.json
mongoexport.exe --uri="XXX" --collection=teams --out=teams.json
mongoexport.exe --uri="XXX" --collection=users --out=users.json